### ISSUE TITLE
A security question, please help to check

### ISSUE THREAD

**Issue by drawcall** [mjeanroy/rollup-plugin-license#1077]
Oh a security question, please help to check

rollup-plugin-license@2.6.1 requires moment@2.29.1

please publish latest package

**Comment by dhilt** [comment]
I believe it relates to https://github.com/mjeanroy/rollup-plugin-license/pull/1074, so the only things that is needed is to release a new version from current "master".

**Comment by ilfa** [comment]
Hi @mjeanroy! Can you publish new version?

**Comment by mjeanroy** [comment]
Hi, version 2.7.0 has just been published 🙂
