### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by jhabdas** [mjeanroy/rollup-plugin-license#11]
http://semver.org/#how-do-i-know-when-to-release-100

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

Would love to see this along with #10.

**Comment by mjeanroy** [comment]
For information, I'll upgrade to version 1.0.0 once rollup release 1.0.0 too. In the meantime, I'll keep it backward compatible.
