### ISSUE TITLE
Relax production dependency versions

### ISSUE THREAD

**Issue by Havunen** [mjeanroy/rollup-plugin-license#1128]
https://github.com/mjeanroy/rollup-plugin-license/blob/master/package.json#L39-L47

It would be nice to not depend on exact version

**Comment by mjeanroy** [comment]
Hi @Havunen,
You are right, when I created this plugin, lockfile did not exist, it makes no sense now!
Fixed [here](https://github.com/mjeanroy/rollup-plugin-license/commit/f8bcd039012791f353baeb2350aaa72e16ece4da), I'll publish a new version soon.
