### ISSUE TITLE
Determining a relevant package.json by version entry as well

### ISSUE THREAD

**Issue by mfranzke** [mjeanroy/rollup-plugin-license#1145]
This is quite similar to the problem reported with https://github.com/mjeanroy/rollup-plugin-license/issues/550

Web Components packages generated with [StencilJS](https://stenciljs.com/) include loader files in a subdirectory, compare to e.g.:
- https://unpkg.com/browse/@duetds/date-picker@1.4.0/dist/loader/package.json
- https://unpkg.com/browse/@telekom/scale-components@3.0.0-beta.55/loader/package.json
- https://unpkg.com/browse/@db-ui/elements@0.13.0/loader/package.json

I like your solution provided with https://github.com/mjeanroy/rollup-plugin-license/commit/d7aeca8f4b81991bc2758306a322945246f742c3 to test for the `"name"` entry in `package.json` and would like to suggest to extend this with testing for the `"version"` entry as well, compare to the `package.json` documentation:
> If you plan to publish your package, the most important things in your package.json are the name and version fields as they will be required.

source: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#name

**Comment by mjeanroy** [comment]
Thanks for the report! It makes sense, thanks for the suggestion!

**Comment by mjeanroy** [comment]
@mfranzke Thanks for the PR, I just released version 2.8.1 with your patch 🙂
