### ISSUE TITLE
Error if license file is a directory

### ISSUE THREAD

**Issue by MichaelKowal** [mjeanroy/rollup-plugin-license#1230]
The scan directory function will get the path to a license and then read the file.  If the file is actually a directory the `fs.readFileSync` function will fail and cause the entire build to fail.  

![image](https://user-images.githubusercontent.com/35471076/191824737-c681ddac-c93c-4f07-bc4c-e1c306c8c135.png)

**Comment by mjeanroy** [comment]
Fixed in `v2.8.2`, thanks @MichaelKowal!
