### ISSUE TITLE
How to use with nuxt 3?

### ISSUE THREAD

**Issue by jojomatik** [mjeanroy/rollup-plugin-license#1261]
Is it possible to use this plugin with nuxt 3 (which uses rollup under the hood as far as I can tell)?

I've tried to add it to the `plugins` section of the `vite` section in the hope that it would pass that down to rollup but with no luck.

The build just freezes unfortunately with no error message or similar. I have to stop the process manually as it will run indefinitely.

```ts
import { defineNuxtConfig } from "nuxt";
import license from "rollup-plugin-license";
import path from "path";

// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  css: ["vuetify/styles"],
  build: {
    transpile: ["vuetify"],
  },
  vite: {
    define: {
      "process.env.DEBUG": "false",
    },
    plugins: [
      license({
        thirdParty: {
          output: path.resolve(__dirname, "./dist/assets/vendor.LICENSE.txt"),
        },
      }),
    ],
  },
});
```

Thanks for helping out :)

**Comment by mjeanroy** [comment]
Hi @jojomatik,
Could you share a repo where I can reproduce your issue?

**Comment by jojomatik** [comment]
I've tested in this repo: https://github.com/jojomatik/nuxt-3-base

Just installed the plugin as a dev-dependency and added above section to the nuxt config.

**Comment by mjeanroy** [comment]
Thanks!
There are two issues here:
- Some dependencies are "virtual dependency": when scanned, the module id is pre-prepended with `virtual:nuxt` prefix.
- The `vite` module is not resolved to an absolute path, I guess this is vite internal behavior.

Both cases lead to an infinite loop when scanning for the related `package.json`.

Thanks for this interesting case, I'll fix it very soon, I'll keep you posted!

**Comment by mjeanroy** [comment]
@jojomatik Should be fixed in version `2.9.1` & `3.0.1` (published a few minutes ago).

**Comment by jojomatik** [comment]
Thanks for the quick fix. Can confirm that it is working :)

Only thing that seems a bit weird to me is that `vue` is not in the output. Should definitely be a runtime dependency. Do you have an immediate clue why that is?

**Comment by jojomatik** [comment]
> Only thing that seems a bit weird to me is that `vue` is not in the output. Should definitely be a runtime dependency. Do you have an immediate clue why that is?

Seems like the vue dependency has been restructured with vue 3 quite a bit. The output seems to contain `@vue/shared`, `@vue/reactivity`, `@vue/runtime-core` and `@vue/runtime-dom`, which seem to be the relevant bundled dependencies. Thanks for the great work on the plugin @mjeanroy!
