### ISSUE TITLE
[Enhancement] Compatible with rollup `4.x`

### ISSUE THREAD

**Issue by cotes2020** [mjeanroy/rollup-plugin-license#1589]
First of all, thank you for your excellent work! 

Perhaps you have also noticed that [rollup 4.0.0](https://github.com/rollup/rollup/releases/tag/v4.0.0) was released on Oct 5, and currently the `rollup-plugin-license` only supports `rollup 3.x`. So please consider an update to it.

https://github.com/mjeanroy/rollup-plugin-license/blob/eafe928c8289e7bf6d837e6ac97dd1a82bdbab08/package.json#L35-L37

## Context

- #1586

**Comment by mjeanroy** [comment]
Thanks @cotes2020! It is fixed in version `v3.2.0` (published a few minutes ago).
