### ISSUE TITLE
package not included in dependencies file

### ISSUE THREAD

**Issue by waruyama** [mjeanroy/rollup-plugin-license#1645]
I noticed that one of the packages used by my project is not included in the dependency files. There is no error or any other message during the build prcess. 

The name of the package is `fflate` (https://github.com/101arrowz/fflate) and upon first inspection I do not see anything out of the ordinary. It is inlcuded in package.json "dependecies" and actually used in the project.

![image](https://github.com/mjeanroy/rollup-plugin-license/assets/43434568/d5ed24f1-62b9-4649-8b60-defbab2b8f25)

I have no idea where to start looking for the root o the problem. ~~The only thing I noticed is that .npmignore includes the "LICENSE" file.~~ (Edit: It is actually not ignored)

Can this be a bug in  `rollup-plugin-license` or more probably a bad configuration in the `fflate` project (or am I doing something wrong)?

**Comment by waruyama** [comment]
as it turned out the package is not being used anymore. Treeshaking did the job and removed the function that was using the package.

While diving into this I found the `debug`option of `rollup-plugin-license`, which helped me find that the package was never even seen by the plugin.

Closing this as not a bug.

**Comment by mjeanroy** [comment]
Thanks for the report @waruyama, and thanks for the follow-up!
