### ISSUE TITLE
Allow adding the license for the package itself into the thirdParty output

### ISSUE THREAD

**Issue by mitar** [mjeanroy/rollup-plugin-license#1685]
I suggest that the `package.json` of the main package is read as well and added to the top of the thirdParty output (in that case though `thirdParty` is badly named, but I think it is still OK). Maybe an option `includeSelf: true`.

The reason for this is that if I make a web app which I license under some license which requires attribution (e.g., MIT) and then deploy that app. The deployed app has to satisfy the license as well for the main code and not just dependencies. So for the main code the requirement is attribution. So it should also be inside the file with all attributions/notices.

It makes even more sense if I imagine somebody else taking my open source web app and deploying it. Deployed app should include the source code license of the whole web app as that somebody is distributing the app.

**Comment by mjeanroy** [comment]
Hi,
I just released version 3.4.0 including the `includeSelf` option (as you suggested!), thanks again for the report :)

**Comment by mitar** [comment]
Awesome! Thank you!

**Comment by mitar** [comment]
I do not see 3.4.0 on NPM? https://www.npmjs.com/package/rollup-plugin-license

**Comment by mjeanroy** [comment]
Oups, good catch @mitar, I forgot to publish, I just did it :)

**Comment by mitar** [comment]
Thanks! I tested it now and I noticed one small issue. I have to set both `includeSelf` and `includePrivate` to include a private self package. I think `includeSelf` should have precedence and allow me to include self no matter if private or not. So that I can then use `includePrivate` to include private dependencies (or not).

**Comment by mjeanroy** [comment]
Hi @mitar,
Sorry for the delay, I just published version 3.4.1 with the fix!

**Comment by mitar** [comment]
Thanks!
