### ISSUE TITLE
[Feature Request] Upgrade glob to latest version

### ISSUE THREAD

**Issue by alyoung1621** [mjeanroy/rollup-plugin-license#1747]
When installing this package, I receive the following NPM warnings:

```
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported.
```

I believe the root issue is the glob version, which is deprecated, and uses inflight, which is also deprecated. Therefore, I would like to request updating the glob version to the latest/supported version. Thank you.

**Comment by mjeanroy** [comment]
Hi @alyoung1621,
Glob usage will be removed (see [PR](https://github.com/mjeanroy/rollup-plugin-license/pull/1742)), I'll close this issue once the new version is publihed on npm.

**Comment by mjeanroy** [comment]
Version 3.5.0 does not depend on glob anymore, which should solve this issue :)
