### ISSUE TITLE
Regression in v3.5.1

### ISSUE THREAD

**Issue by fisker** [mjeanroy/rollup-plugin-license#1753]
Thanks for the great work here.

Prettier is using this plugin, when [upgrading to v3.5.1](https://github.com/prettier/prettier/pull/16430), I found that licences from `emoji-regex`, `ignore`, and `postcss-selector-parser` are not discovered. 

After some investigation, I found their license are named [LICENSE-MIT](https://unpkg.com/browse/ignore@5.3.1/LICENSE-MIT).

Reading this line https://github.com/mjeanroy/rollup-plugin-license/blob/c905ef6ec861511490a2dc8083f33564939e8bea/src/license-plugin.js#L205, it seems they are not intentionally to be found... Anyway, obviously they are licenses, I don't want remove them now, so should we found `LICENSE-MIT`(maybe other people use `LICENSE-*`?) file  by default? Or should we make the filenames configurable?

**Comment by bluwy** [comment]
I noticed this is happening in Vite for `cssesc` and `postcss-selector-parser` too. `cssesc` is a little unique with `LICENSE-MIT.txt`

**Comment by mjeanroy** [comment]
Hi,
Very sorry for that.
It should be fixed in v3.5.2, please let me know if it does not work for you.
