### ISSUE TITLE
fix Rollup 1.0 deprecated hooks: "transformBundle" and "ongenerate"

### ISSUE THREAD

**Issue by revelt** [mjeanroy/rollup-plugin-license#284]
According to warning messages in unit tests currently, the following hooks should be updated:

`transformBundle` hook -> `renderChunk` hook
`ongenerate` hook -> `generateBundle` hook

I tried forking and patching but it is beyond trivial function renaming, I won't be able to help here.

Thank you Mickael and everybody who contributed for this plugin.

**Comment by mjeanroy** [comment]
Hi @revelt, I've been noticed about these warnings with #283.
The fix should be released in the next few days ;)

**Comment by jharris4** [comment]
@mjeanroy In case it helps, `rollup-plugin-analyzer` just released an update for these same deprecation warnings, and the commit for that is here: https://github.com/doesdev/rollup-plugin-analyzer/commit/506d93f942dce5e076312bd1642aed182fe12a60

**Comment by mjeanroy** [comment]
@revelt @jharris4 Version 0.8.0 has been released, adding compatibility with rollup >= 1.0.0, please let me knows if something does not work.

**Comment by revelt** [comment]
Thank you, all look good, warning messages are gone. 👍
