### ISSUE TITLE
Suggestion: Use tree-shaking information when generating third party dependencies

### ISSUE THREAD

**Issue by lukastaegert** [mjeanroy/rollup-plugin-license#380]
At the moment, this plugin will list all imported dependencies in the license file even though I may not be using any code from those dependencies due to tree-shaking.

This could be improved substantially by not relying on the load hook to identify dependencies but instead by using the bundle information in generateBundle, which lists for each chunk the module ids included in the chunk + the rendered length (which should be 0 for tree-shaken modules).

**Comment by mjeanroy** [comment]
Hi @lukastaegert,
Thanks for the report.
You're totally right, the license should be excluded if the dependency does not appear in the final bundle. I suppose the idea here is to use the `modules` entry in the `ChunkInfo` parameter, right?

**Comment by mjeanroy** [comment]
@lukastaegert I opened a pull request for this, if you few minutes to take a look and tell me if I missed something ;)

**Comment by lukastaegert** [comment]
I can take a look this evening, thanks for being responsive to this!

**Comment by lukastaegert** [comment]
Ok, did it right away, thanks!

**Comment by mjeanroy** [comment]
Hi,
Version 0.10.0 has been published with this feature.
