### ISSUE TITLE
[Fix Prototype Pollution Audit Warning] v0.9.0 still uses lodash <4.17.12

### ISSUE THREAD

**Issue by poorejc** [mjeanroy/rollup-plugin-license#422]
rollup-plugin-license still uses lodash v4.17.11, which still audits with a Prototype Pollution vulnerability. lodash is patched in v4.17.12. Should be trivial to update package.json to include patched version of lodash. Thanks--great package, big help in Apache .js projects.

![Screen Shot 2019-07-25 at 8 55 42 PM](https://user-images.githubusercontent.com/12189190/61918275-cf1a5580-af1e-11e9-9048-86646589838a.png)

**Comment by papeloto** [comment]
Same issue here. As you said, it should be easy to fix.
Thanks!

**Comment by mjeanroy** [comment]
Hi,
Thanks for the report.
It should be fixed with version 0.10.0.

**Comment by poorejc** [comment]
Thanks!
