### ISSUE TITLE
Consider using minor semver changes for releases

### ISSUE THREAD

**Issue by jharris4** [mjeanroy/rollup-plugin-license#429]
Hi, I've been using this plugin for a while, and it works great, thanks for the great work!

We periodically update our build packages, using the `yarn outdated` command, and whenever there is a release of this plugin it is considered a breaking change because the version is in the pattern `0.x.y`.

This is compared to other packages such as `file-loader` in the sample below (notice in the difference in how the "Wanted" version gets calculated):

```
yarn outdated
yarn outdated v1.17.3
Package               Current Wanted Latest Workspace         Package Type URL                                              
file-loader           4.1.0   4.2.0  4.2.0  @porterjs/webpack dependencies https://github.com/webpack-contrib/file-loader   
rollup-plugin-license 0.10.0  0.10.0 0.11.0 @porterjs/rollup  dependencies https://github.com/mjeanroy/rollup-plugin-license
✨  Done in 2.57s.
```

Would you be open to the possibility of either bumping the next version to `1.0.0` so that future releases can be `1.x.0` or `1.0.y`?

Failing that, for small non-breaking changes perhaps you could only bump the minor version, so the previous release might have been `0.10.0` -> `0.10.1`.

**Comment by mjeanroy** [comment]
Hi,

> Hi, I've been using this plugin for a while, and it works great, thanks for the great work!

Thanks :heart: 

> Would you be open to the possibility of either bumping the next version to 1.0.0 so that future releases can be 1.x.0 or 1.0.y?

Once #379 and #381 will be done, I think it will be time to release `1.0.0`. Until that, I plan to release two version : `0.12.0` (with #379) and `0.13.0` (with #381). Do you think it will be a problem for you?

> Failing that, for small non-breaking changes perhaps you could only bump the minor version, so the previous release might have been 0.10.0 -> 0.10.1.

So, you mean the `patch` version? :wink:

**Comment by jharris4** [comment]
Sure, the version range wasn't a real problem, more of a suggestion for improvement.

Releasing `1.0.0` when you're ready sounds like a great idea to me!

**Comment by mjeanroy** [comment]
Hi @jharris4,

For information, version 1.0.0 has just been published. This version do not support rollup < 1 and do not support deprecated options anymore.

Note that version 2.0.0 has also been published, the main difference is that node < 10 is not "officially" supported, since rollup 2.x.x also removed support for node < 10.
