### ISSUE TITLE
DocBlocks for Licenses

### ISSUE THREAD

**Issue by jhabdas** [mjeanroy/rollup-plugin-license#5]
JavaScript libraries have traditionally output doc blocks for licenses like the following, plucked from the [3.2.1 jQuery slim build](https://cdn.jsdelivr.net/jquery/3.2.1/jquery.slim.min.js):

```js
/*! jQuery v3.2.1 -ajax,-ajax/jsonp,-ajax/load,-ajax/parseXML,-ajax/script,-ajax/var/location,-ajax/var/nonce,-ajax/var/rquery,-ajax/xhr,-manipulation/_evalUrl,-event/ajax,-effects,-effects/Tween,-effects/animatedSelector | (c) JS Foundation and other contributors | jquery.org/license */
```

Notice the block is prefixed with `/*!`. IIRC this is a de facto standard originating as early as (if not earlier than) the [YUI compressor](https://yui.github.io/yuicompressor/), and was created to signal special handling of those blocks and to never strip them from code (for legal reasons).

Let us implement this in Rollup Plugin License.

**Comment by mjeanroy** [comment]
Hi @jhabdas,

I don't understand what is your request, I would be happy to help you but can you explain more? Would you like an option to generate in the final bundle a comment block starting with `/*!`?

Thanks!

**Comment by jhabdas** [comment]
> Would you like an option to generate in the final bundle a comment block starting with `/*!`?

Perhaps, but I felt it better to start a discussion first as it's been a while since I've delved into this topic and wanted to open this issue to raise visibility.

> I would be happy to help you but can you explain more?

https://github.com/yui/yuicompressor/blob/master/README.md#notes

> C-style comments starting with /*! are preserved. This is useful with comments containing copyright/license information. As of 2.4.8, the '!' is no longer dropped by YUICompressor.

Other compressors, like Uglify for example, retain comments if they have `@license` (or maybe `@copyright`?) in a doc block, but that doesn't prevent post compressors running as a part of a CI process, for example, from stripping licenses from inline JS when run through an HTML compressor following this pseudo-standard (I'm unaware of any official specs, but it's commonly followed my major libraries I believe).

**Comment by mjeanroy** [comment]
I know how this prefix, indeed it is already handled (see it [here](https://github.com/mjeanroy/rollup-plugin-license/blob/v0.4.0/src/license-plugin.js#L179)): if the license header you want to prepend to your bundle is already a block comment (starting with `/**` or `/*!`), it will just be prepended to the bundle as it is.

What you want here seems to use `/*!` to generate a block comment if it's not one already. I'm not sure it should be the default, but I agree, it could probably be useful to add an option for that.

**Comment by jhabdas** [comment]
@mjeanroy point the way and I'll try to work on a pull. my use case this thusly:

```
plugins: [
    license({
      banner: `pithy banner stuff and whatnot`
    })
  ]
```

I output the banner atop my dist files in conjunction with `uglify`. The only other mystery I have I'd like to try and solve (ideally with the pull for time savings) is this:

**Example banner output do `/dist`:**

```js
/**
 * Banner stuff
 */

!function(...) /** code **/
```

Note the _whitespace_ above the uglified code block and below the banner doc block. Have you seen that at all? Not sure if it's an interop thing with uglify or what but I'd love to nix it.

**Comment by jhabdas** [comment]
@mjeanroy sorry if that last comment was info overload. trying to be as succinct as possible. if you have any pointers on where I should start hacking to achieve what I'm looking for WRT please LMK.

**Comment by jhabdas** [comment]
Forked

**Comment by jhabdas** [comment]
Unforked. No need for update. Looks like the comment in https://github.com/mjeanroy/rollup-plugin-license/issues/5#issuecomment-301455206 applies to banners too, and not just block comments, enabling one to achieve a one-line banner with guard against compressors like so:

```js
license({
      banner: `/*! Fetch Inject v<%= pkg.version %> Copyright (c) <%= moment().format('YYYY') %> Josh Habdas @license ISC */`
    })
```
