### ISSUE TITLE
rollup-plugin-license@0.13.0" has incorrect peer dependency "rollup@< 2"

### ISSUE THREAD

**Issue by jharris4** [mjeanroy/rollup-plugin-license#521]
Hi! rollup version 2 was recently released, and it seems like this plugin works fine with rollup v2, but there is a warning during installation:

`rollup-plugin-license@0.13.0" has incorrect peer dependency "rollup@< 2"`

Perhaps we can update the `package.json` to have the peer dependency `"rollup": "< 3"` ?

**Comment by mjeanroy** [comment]
Hi @jharris4,
Sorry for the delay, but It should be ok with latest versions now.
