### ISSUE TITLE
Dependency "null" does not specify any license when depending on @babel/runtime

### ISSUE THREAD

**Issue by lazka** [mjeanroy/rollup-plugin-license#550]
Minimal reproducer: https://github.com/lazka/rollup-plugin-license-bug

My package depends on i18next which in turn depends on @babel/runtime. @babel/runtime for some reason contains a "package.json" in a subdirectory which just contains:

```
{
  "type": "module"
}
```

rollup-plugin-license will interpret this as a dependency, but with all information missing everything will fail.

**Comment by mjeanroy** [comment]
Hi @lazka,
Thanks for the report, and thanks for the repo!

The problem here is due to the fact that a `package.json` is set in `@babel/runtime/esm` to specify that modules in this directory use ESM imports/exports.

I just pushed the fix, the next release should be available on npm soon.

**Comment by mjeanroy** [comment]
@lazka Version 1.0.1 & 2.0.1 have been published with the fix.

**Comment by lazka** [comment]
Thanks! And thanks for this nice plugin!
