### ISSUE TITLE
TypeError: Cannot read property 'names' of undefined

### ISSUE THREAD

**Issue by kossolax** [mjeanroy/rollup-plugin-license#6]
Hello,

 I've just updated to version 0.4 and it doesn't work anymore.

[10:18:18] TypeError: Cannot read property 'names' of undefined
    at new Link (C:\[...]\node_modules\rollup\dist\rollup.js:8993:18)
    at C:\[...]\node_modules\rollup\dist\rollup.js:9133:12
    at Array.forEach (native)
    at collapseSourcemaps (C:\[...]\node_modules\rollup\dist\rollup.js:9132:23)
    at Bundle$$1.render (C:\[...]\node_modules\rollup\dist\rollup.js:9724:10)
    at Object.generate (C:\[...]\node_modules\rollup\dist\rollup.js:9915:26)
    at C:\[...]\bundle.js:64:25
    at process._tickCallback (internal/process/next_tick.js:103:7)

    "rollup": "^0.41.6",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-license": "^0.4.0",
    "rollup-plugin-typescript2": "^0.4.1",
    "rollup-plugin-uglify": "^1.0.2",

**Comment by kossolax** [comment]
Looks like not to be related to 0.4. But it's seems incompatible with rollup 0.41.

**Comment by mjeanroy** [comment]
@kossolax Thanks for your report. I check it, and I'll release a new version once fixed.

**Comment by mjeanroy** [comment]
Hi, I just add test with rollup 0.41, and I cannot reproduce the problem. Can you share your configuration?

**Comment by kossolax** [comment]
I've tried to disable uglify and babel which could potentially interfere, but issue still.
 I've also tried with empty LICENSE file.

part of package.json:
```
  "devDependencies": {
    "@alexlur/rollup-plugin-typescript": "^1.0.4",
    "babel-preset-es2015-rollup": "^3.0.0",
    "fs-jetpack": "^1.0.0",
    "gulp": "^3.9.1",
    "gulp-less": "^3.3.0",
    "jshint": "^2.9.4",
    "mocha": "^3.4.1",
    "rollup": "^0.41.6",
    "rollup-plugin-babel": "^2.7.1",
    "rollup-plugin-license": "^0.4.0",
    "rollup-plugin-uglify": "^1.0.2",
    "ts-node": "^3.0.4",
    "tslint": "^5.2.0",
    "typescript": "^2.3.2",
    "typings": "^2.1.1"
  }
```

part of bundler.js
```
const path = require("path");
const jetpack = require("fs-jetpack");
const rollup = require("rollup").rollup;
const minify = require("uglify-js").minify;
const uglify = require("rollup-plugin-uglify");
const babel = require("rollup-plugin-babel");
const license = require("rollup-plugin-license");
const rollupTS = require("@alexlur/rollup-plugin-typescript");
const typescript = require("typescript");

[...]
let cached = {};

module.exports = function (src, dest, env) {

  let plugins = [];

//  plugins.push(license({sourceMap: true, banner: path.join(__dirname, "LICENSE")}));
  plugins.push(rollupTS({typescript: typescript}));
  plugins.push(babel());

  const json = jetpack.read("config/env.json", "json");

  if( !json.debug )
    plugins.push(uglify({mangle: {toplevel: true, eval: true]},  output: { comments: /XXXX/} }, minify));


  return rollup({
    entry: src,
    external: generateExternalModulesList(),
    cache: cached[src],
    plugins: plugins
  })
  .then(function (bundle) {
    cached[src] = bundle;

    let jsFile = path.basename(dest);
    let result = bundle.generate({
        moduleName: "Designer",
        format: env === "web" ? "umd" : "cjs",
        intro: env === "web" ? intro() : "",
        outro: env === "web" ? outro() : "",
        sourceMap: json.debug,
        sourceMapFile: jsFile
    });
    return Promise.all([
        jetpack.writeAsync(dest, result.code + (json.debug ? "\n//# sourceMappingURL=" + jsFile + ".map" : "") ),
        jetpack.writeAsync(dest + ".map", json.debug ? result.map.toString() : ""),
    ]);
  });
};

```

**Comment by mjeanroy** [comment]
@kossolax Thank you. Does the problem appear when you enable or disable source map (i.e what is the value of `json.debug` when the build fail)?

**Comment by mjeanroy** [comment]
@kossolax Ok, I found the problem. The cause is that you should enable `sourceMap` option in both `rollup.rollup` and `rollup.generate` functions.

This plugin listen to the rollup `options` callback to enable/disable `sourceMap`, the downside is that the flag has to be set when `rollup.rollup` is called. I'm going to fix this, but in the meantime this is the workaround ;)

**Comment by kossolax** [comment]
The workaround works, thanks!

2017-05-16 13:53 GMT+02:00 Mickael Jeanroy <notifications@github.com>:
