### ISSUE TITLE
Hi, can we please have new release?

### ISSUE THREAD

**Issue by Havunen** [mjeanroy/rollup-plugin-license#736]
We are getting warnings from yarn saying that moment 2.27 is not compatible with our local version 2.29.1 

rollup-plugin-license@2.2.0:
  version "2.2.0"
  resolved "https://registry.yarnpkg.com/rollup-plugin-license/-/rollup-plugin-license-2.2.0.tgz#0d19139bbe44dda500fbf15530af07c91949e348"
  integrity sha512-xXb1vviEwlJMX+VGUSsglcMA/Rh9d2QzEm94awy4FlnsPqGrXoTYYGOR3UXR6gYIxiJFkr7qmkKF/NXfre/y8g==
  dependencies:
    commenting "1.1.0"
    glob "7.1.6"
    lodash "4.17.19"
    magic-string "0.25.7"
    mkdirp "1.0.4"
    moment "2.27.0"
    package-name-regex "1.0.8"
    spdx-expression-validate "2.0.0"
    spdx-satisfies "5.0.0"
    
 It seems this plugin wants exactly version "2.27.0" :( can this version requirement be relaxed?
 
 I also noticed that these version are bumped in master branch? Can we have all dependencies updated and new release please ❤️ ?

**Comment by Havunen** [comment]
ping @mjeanroy

**Comment by mjeanroy** [comment]
@Havunen Ah ah, just push the tag for the new version while you pinged me, I'll publish `2.3.0` in few minutes ;)

**Comment by mjeanroy** [comment]
@Havunen It's published, it should be available now (or in a few minutes)

**Comment by Havunen** [comment]
Thank you :)
